### ISSUE TITLE
AccioHacks

### ISSUE THREAD

**Issue by BannerBomb** [pvrs12/WiiCodeFetcher#2]
Since accio hacks dont work anymore cant you reverse engineer the AccioHacks app and build a duplicate with your own server that still works with geckocodes?

**Comment by pvrs12** [comment]
I'm not sure what you mean. I know AccioHacks no longer works (which is why I wrote this initially), but this program should still work with geckocodes. I just tested it by downloading the codes for Super Smash Bros Brawl (RSBE01) from geckocodes.

**Comment by BannerBomb** [comment]
yes this app works never mind but thanks for releasng it at least we have something to get codes from now besides using a computer

**Comment by BannerBomb** [comment]
hey i have this code that i want to get out to ppl that i created for Mario Kart Wii [RMCE01] its an item code but with better well thought out button activators this hack also has a no item function so you can get rid of your item to be able to get Item Boxes too and this code works online/offline but not 2 players yet thats why i created another hack that supports 2 players but it couldnt handle the no item function... so can you publish the code to help me get it out to people please?

**Comment by pvrs12** [comment]
Wish I could, but I don't know how to get them published to a site like geckocodes. If it's only a few people you could probably just send them the text files yourself. If you're trying to get them out to the world you could try joining geckocodes and publishing there. [Here](http://geckocodes.org/index.php?chid=R&r=*&hacker=join) is a link with some info on that. 

Glad it works for you and sorry I can't help you more

**Comment by BannerBomb** [comment]
i tried joining them but they never emailed me back i emailed james a ******\* but never emailed back its been like 2 years now

Edit: I censored out the email, just in case he doesn't want it posted here

**Comment by pvrs12** [comment]
Maybe you can get in contact with someone who has recently posted codes and ask them if they would post on your behalf. It looks like the most recent poster is [this guy](geckocodes.org/index.php?chid=R&r=*&hacker=Thomas83Lin)

**Comment by BannerBomb** [comment]
thanks ill try

**Comment by BannerBomb** [comment]
error 404 page not found

**Comment by BannerBomb** [comment]
nvm
